---
ID: "dab7ec96-38c0-44f2-a0df-9ac07d818608"
Parent: "7d1d2c02-8a38-4fac-9f66-400b9f0f6b18"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: /sitecore/media library/Project/Verticals/Financial2/Home page/Carousels/Default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6a8c25d5-421e-4eff-8ca9-f992444b2a5b"
