---
ID: "df9a2bae-0655-40a8-beb0-a81e403e2786"
Parent: "38ddc80a-62d2-4fe5-86f8-dd7b7a076b20"
Template: "38ddc80a-62d2-4fe5-86f8-dd7b7a076b20"
Path: /sitecore/templates/Project/BNSF/Pages/Author Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {1226C3C7-2D1F-48F5-87B4-C1DA459F05E5}
    {F83CCEFD-FC41-4A60-9882-8F7EA5CF41A8}
    {14431DCE-508D-4D54-9D04-C22ABBDC8F83}
- ID: "17539b8f-42e0-473d-8ae6-708671b9e49e"
  Hint: Photo
  Value: |
    <image mediaid="{62F6A36E-BFB0-432D-8502-B8E7E9F1E90A}" alt="Olly Bio Image" height="" width="" hspace="" vspace="" />
- ID: "a8c9cf02-23bd-477f-873c-f0a5e7e45a7c"
  Hint: BackgroundImage
  Value: |
    <image mediaid="{DC65B8CF-63A5-424E-A739-3B6345F75F92}" />
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{E9B6C600-C6E8-4867-BCB7-8B0DC5F19840}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "00f61f69-279a-4d9f-83ff-7268b6bad945"
      Hint: SocialIcon3
      Value: |
        <image mediaid="{D7668912-4C04-4881-8C8B-3EEDBC4277A6}" />
    - ID: "2bd601a1-7fcf-478e-9ecb-725c5dc0d3ec"
      Hint: SocialLink3
      Value: |
        <link linktype="external" url="http://www.twitter.com" anchor="" target="" />
    - ID: "43c0f89a-5709-4441-8a10-67bbb3410716"
      Hint: SocialIcon2
      Value: |
        <image mediaid="{B5E0C7F5-5693-4875-B68F-70B99E7F34EF}" />
    - ID: "4ad6c337-b19c-42e7-ad36-62dd055b8c76"
      Hint: Position
      Value: Product Specialist
    - ID: "812643bc-1cb6-475a-8b9a-db3cc1beb670"
      Hint: SocialIcon1
      Value: |
        <image mediaid="{37E8F17D-5AA1-4AF4-9CB1-45C4F07BDD4C}" />
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "18ea5f0e-c3f6-498c-87c5-78ae7676b89f"
    - ID: "d641b298-b3f9-4274-a5f4-62fbfa13547c"
      Hint: SocialLink1
      Value: |
        <link linktype="external" url="http://www.facebook.com" anchor="" target="" />
    - ID: "da698ec2-89df-4fe4-8be7-9e7333a9d577"
      Hint: Name
      Value: $name
    - ID: "dfaf83d0-c504-473a-beae-1c1e367e8111"
      Hint: SocialLink2
      Value: |
        <link linktype="external" url="http://www.instagram.com" anchor="" target="" />
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "4ad6c337-b19c-42e7-ad36-62dd055b8c76"
      Hint: Position
      Value: Spécialiste Produit
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "22dc588e-68b4-4aa1-a19f-23a5a6282378"
    - ID: "da698ec2-89df-4fe4-8be7-9e7333a9d577"
      Hint: Name
      Value: $name
